
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autotest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import threading
from wir import *
from loguru import logger
from runtest import MainTest
from libs.can.zlg.zlgMain import *
from PyQt5 import QtCore, QtWidgets
from libs.logger.logger import Logger
from PyQt5.QtCore import pyqtSignal, QObject
"""
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# 设置Qt插件路径
if hasattr(sys, 'real_prefix') or hasattr(sys, 'base_prefix'):
    qt_base = os.path.join(sys.prefix, "Lib", "site-packages", "PyQt5", "Qt5")
    os.environ["QT_PLUGIN_PATH"] = os.path.join(qt_base, "plugins")
    os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = os.path.join(qt_base, "plugins", "platforms")
"""
Logger()

class Ui_Form(QObject,MainTest):
    new_log_signal = pyqtSignal(str)
    test_finished_signal = pyqtSignal(str)  # 测试完成信号，携带错误信息(空字符串表示无错误)
    def __init__(self):
        super().__init__()
        self.listWidget = None
        self.scrollAreaWidgetContents_2 = None
        self._test_thread = None
        self._test_stop_flag = False

    def setupUi(self, Form):
        if hasattr(self, "ui_sink_id"):
            try:
                logger.remove(self.ui_sink_id)
            except:
                pass
        Form.setObjectName("Form")
        Form.resize(1176, 635)
        # 允许窗口自由缩放（拖边缘 / 最大化 / 最小化），设定一个最小尺寸避免控件挤压变形
        Form.setMinimumSize(QtCore.QSize(800, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        # ============================ tab: 功能测试 ============================
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_tab1 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_tab1.setObjectName("horizontalLayout_tab1")
        self.verticalLayout_btns = QtWidgets.QVBoxLayout()
        self.verticalLayout_btns.setObjectName("verticalLayout_btns")
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setMinimumSize(QtCore.QSize(120, 38))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_btns.addWidget(self.pushButton_14)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 38))
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_btns.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 38))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_btns.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(120, 38))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_btns.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 38))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_btns.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_btns.addItem(spacerItem1)
        self.horizontalLayout_tab1.addLayout(self.verticalLayout_btns)
        self.treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_tab1.addWidget(self.treeView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        # ============================ tab_2: 压力测试 ============================
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_tab2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_tab2.setObjectName("verticalLayout_tab2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget(self.tab_2)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_tab2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_tab2.setObjectName("horizontalLayout_tab2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_group = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_group.setObjectName("verticalLayout_group")
        # ---- 第一行：连接类按钮 ----
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.get_pushButton_5)
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.get_pushButton_6)
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.get_pushButton_7)
        self.verticalLayout_10.addWidget(self.pushButton_7)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.get_pushButton_16)
        self.verticalLayout_10.addWidget(self.pushButton_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.get_pushButton_8)
        self.verticalLayout_11.addWidget(self.pushButton_8)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.get_pushButton_17)
        self.verticalLayout_11.addWidget(self.pushButton_17)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.get_pushButton_20)
        self.verticalLayout_14.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(self.get_pushButton_21)
        self.verticalLayout_14.addWidget(self.pushButton_21)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_56 = QtWidgets.QLabel(self.groupBox)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_13.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.groupBox)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_13.addWidget(self.label_57)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setMaximumWidth(150)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_12.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setMaximumWidth(150)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_12.addWidget(self.lineEdit_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_9.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_9.addWidget(self.radioButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setMaximumWidth(150)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_8.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMaximumWidth(150)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_group.addLayout(self.horizontalLayout_2)
        # ---- 第二行：CAN 设置 ----
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.get_pushButton_13)
        self.verticalLayout_15.addWidget(self.pushButton_13)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(self.get_pushButton_19)
        self.verticalLayout_15.addWidget(self.pushButton_19)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.clicked.connect(self.get_pushButton_18)
        self.verticalLayout_16.addWidget(self.pushButton_18)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.get_pushButton_15)
        self.verticalLayout_16.addWidget(self.pushButton_15)
        self.horizontalLayout_3.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_17.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentTextChanged.connect(self.get_comboBox)
        self.verticalLayout_18.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.currentTextChanged.connect(self.get_comboBox_2)
        self.verticalLayout_18.addWidget(self.comboBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_53 = QtWidgets.QLabel(self.groupBox)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_19.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.groupBox)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_19.addWidget(self.label_54)
        self.horizontalLayout_3.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.currentTextChanged.connect(self.get_comboBox_8)
        self.verticalLayout_20.addWidget(self.comboBox_8)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.currentTextChanged.connect(self.get_comboBox_7)
        self.verticalLayout_20.addWidget(self.comboBox_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_52 = QtWidgets.QLabel(self.groupBox)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_21.addWidget(self.label_52)
        self.label_55 = QtWidgets.QLabel(self.groupBox)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_21.addWidget(self.label_55)
        self.horizontalLayout_3.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.currentTextChanged.connect(self.get_comboBox_6)
        self.verticalLayout_22.addWidget(self.comboBox_6)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.currentTextChanged.connect(self.get_comboBox_5)
        self.verticalLayout_22.addWidget(self.comboBox_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_22)
        self.verticalLayout_group.addLayout(self.horizontalLayout_3)
        # ---- 第三行：用例选择（40 个复选框，4 列） ----
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_12.clicked.connect(self.get_checkBox_12)
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_15.clicked.connect(self.get_checkBox_15)
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_13.clicked.connect(self.get_checkBox_13)
        self.verticalLayout_3.addWidget(self.checkBox_13)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_5.clicked.connect(self.get_checkBox_5)
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_10.clicked.connect(self.get_checkBox_10)
        self.verticalLayout_3.addWidget(self.checkBox_10)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.clicked.connect(self.get_checkBox)
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.clicked.connect(self.get_checkBox_4)
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_6.clicked.connect(self.get_checkBox_6)
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_9.clicked.connect(self.get_checkBox_9)
        self.verticalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.clicked.connect(self.get_checkBox_3)
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_14.clicked.connect(self.get_checkBox_14)
        self.verticalLayout_4.addWidget(self.checkBox_14)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_16.clicked.connect(self.get_checkBox_16)
        self.verticalLayout_4.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_17.clicked.connect(self.get_checkBox_17)
        self.verticalLayout_4.addWidget(self.checkBox_17)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_7.clicked.connect(self.get_checkBox_7)
        self.verticalLayout_4.addWidget(self.checkBox_7)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_11.clicked.connect(self.get_checkBox_11)
        self.verticalLayout_4.addWidget(self.checkBox_11)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.clicked.connect(self.get_checkBox_2)
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_8.clicked.connect(self.get_checkBox_8)
        self.verticalLayout_4.addWidget(self.checkBox_8)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_18.clicked.connect(self.get_checkBox_18)
        self.verticalLayout_4.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_19.clicked.connect(self.get_checkBox_19)
        self.verticalLayout_4.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_20.clicked.connect(self.get_checkBox_20)
        self.verticalLayout_4.addWidget(self.checkBox_20)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_21.clicked.connect(self.get_checkBox_21)
        self.verticalLayout_5.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_22.clicked.connect(self.get_checkBox_22)
        self.verticalLayout_5.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_23.clicked.connect(self.get_checkBox_23)
        self.verticalLayout_5.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_24.clicked.connect(self.get_checkBox_24)
        self.verticalLayout_5.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_25.clicked.connect(self.get_checkBox_25)
        self.verticalLayout_5.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_26.clicked.connect(self.get_checkBox_26)
        self.verticalLayout_5.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_27.clicked.connect(self.get_checkBox_27)
        self.verticalLayout_5.addWidget(self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_28.clicked.connect(self.get_checkBox_28)
        self.verticalLayout_5.addWidget(self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_29.clicked.connect(self.get_checkBox_29)
        self.verticalLayout_5.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_30.clicked.connect(self.get_checkBox_30)
        self.verticalLayout_5.addWidget(self.checkBox_30)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_31.clicked.connect(self.get_checkBox_31)
        self.verticalLayout_6.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_32.setObjectName("checkBox_32")
        self.checkBox_32.clicked.connect(self.get_checkBox_32)
        self.verticalLayout_6.addWidget(self.checkBox_32)
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_33.setObjectName("checkBox_33")
        self.checkBox_33.clicked.connect(self.get_checkBox_33)
        self.verticalLayout_6.addWidget(self.checkBox_33)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_34.setObjectName("checkBox_34")
        self.checkBox_34.clicked.connect(self.get_checkBox_34)
        self.verticalLayout_6.addWidget(self.checkBox_34)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_35.clicked.connect(self.get_checkBox_35)
        self.verticalLayout_6.addWidget(self.checkBox_35)
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_36.clicked.connect(self.get_checkBox_36)
        self.verticalLayout_6.addWidget(self.checkBox_36)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_37.clicked.connect(self.get_checkBox_37)
        self.verticalLayout_6.addWidget(self.checkBox_37)
        self.checkBox_38 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_38.clicked.connect(self.get_checkBox_38)
        self.verticalLayout_6.addWidget(self.checkBox_38)
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_39.clicked.connect(self.get_checkBox_39)
        self.verticalLayout_6.addWidget(self.checkBox_39)
        self.checkBox_40 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_40.clicked.connect(self.get_checkBox_40)
        self.verticalLayout_6.addWidget(self.checkBox_40)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_group.addWidget(self.groupBox_2, 1)
        self.horizontalLayout_tab2.addWidget(self.groupBox, 3)
        # ---- 右侧日志列表 ----
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget.setMinimumWidth(300)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setStyleSheet("QListWidget::item{height:22px;}")
        self.horizontalLayout_tab2.addWidget(self.listWidget, 2)
        #绑定信号
        self.new_log_signal.connect(self.append_log_to_list)
        self.test_finished_signal.connect(self._on_test_finished)
        #注册UI日志回调，固定唯一ID
        #保存sink标识
        self.ui_sink_id = logger.add(
            self._ui_log_sink,
            format="{time:YYYY-MM-DD HH:mm:ss} {level: <8} {message}",
            level="INFO"
        )
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_tab2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        # ============================ tab_3: monkey测试 ============================
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_tab3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_tab3.setObjectName("verticalLayout_tab3")
        self.horizontalLayout_top3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top3.setObjectName("horizontalLayout_top3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_top3.addWidget(self.pushButton_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top3.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_top3.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setMaximumWidth(140)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_top3.addWidget(self.lineEdit_3)
        self.verticalLayout_tab3.addLayout(self.horizontalLayout_top3)
        self.horizontalLayout_main3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main3.setObjectName("horizontalLayout_main3")
        self.verticalLayout_pkg = QtWidgets.QVBoxLayout()
        self.verticalLayout_pkg.setObjectName("verticalLayout_pkg")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_pkg.addWidget(self.label_6)
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setObjectName("listView")
        self.verticalLayout_pkg.addWidget(self.listView)
        self.horizontalLayout_main3.addLayout(self.verticalLayout_pkg, 2)
        self.verticalLayout_mid3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_mid3.setObjectName("verticalLayout_mid3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_mid3.addItem(spacerItem3)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_mid3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_mid3.addWidget(self.pushButton_11)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_mid3.addItem(spacerItem4)
        self.horizontalLayout_main3.addLayout(self.verticalLayout_mid3)
        self.verticalLayout_white = QtWidgets.QVBoxLayout()
        self.verticalLayout_white.setObjectName("verticalLayout_white")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_white.addWidget(self.label_7)
        self.listView_2 = QtWidgets.QListView(self.tab_3)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_white.addWidget(self.listView_2)
        self.horizontalLayout_main3.addLayout(self.verticalLayout_white, 2)
        self.verticalLayout_evt = QtWidgets.QVBoxLayout()
        self.verticalLayout_evt.setObjectName("verticalLayout_evt")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_evt.addWidget(self.label_10)
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_evt.addWidget(self.tableView, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_evt.addWidget(self.label_11)
        self.tableView_2 = QtWidgets.QTableView(self.tab_3)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_evt.addWidget(self.tableView_2, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_evt.addWidget(self.radioButton_6)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_evt.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_evt.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_evt.addWidget(self.radioButton_5)
        self.horizontalLayout_main3.addLayout(self.verticalLayout_evt, 3)
        self.verticalLayout_tab3.addLayout(self.horizontalLayout_main3, 1)
        self.tabWidget.addTab(self.tab_3, "")
        # ============================ tab_4: 性能测试 ============================
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_tab4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_tab4.setObjectName("verticalLayout_tab4")
        self.horizontalLayout_top4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top4.setObjectName("horizontalLayout_top4")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_12.setMinimumWidth(110)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_top4.addWidget(self.pushButton_12)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top4.addItem(spacerItem5)
        self.verticalLayout_tab4.addLayout(self.horizontalLayout_top4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_tab4.addWidget(self.groupBox_3, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_tab4.addWidget(self.groupBox_4, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_tab4.addWidget(self.groupBox_5, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_tab4.addWidget(self.groupBox_6, 1)
        self.tabWidget.addTab(self.tab_4, "")
        # ============================ tab_5: 设备详情 ============================
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_tab5 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_tab5.setObjectName("verticalLayout_tab5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 1, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_7)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_7)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 2, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_7)
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 3, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_7)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 3, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_7)
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 3, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 4, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 4, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 4, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_7)
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 4, 3, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_7.setColumnStretch(3, 1)
        self.verticalLayout_tab5.addWidget(self.groupBox_7, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_8)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_8)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_8)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_8)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 2, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_8)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 3, 3, 1, 1)
        self.gridLayout_8.setColumnStretch(1, 1)
        self.gridLayout_8.setColumnStretch(3, 1)
        self.verticalLayout_tab5.addWidget(self.groupBox_8, 2)
        self.horizontalLayout_bottom5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottom5.setObjectName("horizontalLayout_bottom5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13, 1)
        self.horizontalLayout_bottom5.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14, 1)
        self.horizontalLayout_bottom5.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 1, 1, 1, 1)
        self.gridLayout_11.setColumnStretch(1, 1)
        self.horizontalLayout_bottom5.addWidget(self.groupBox_11, 1)
        self.verticalLayout_tab5.addLayout(self.horizontalLayout_bottom5, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)


        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "压力测试工具"))
        self.pushButton.setText(_translate("Form", "用例生成"))
        self.pushButton_2.setText(_translate("Form", "用例加载"))
        self.pushButton_3.setText(_translate("Form", "用例执行"))
        self.pushButton_4.setText(_translate("Form", "生成报告"))
        self.pushButton_14.setText(_translate("Form", "元素定位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "功能测试"))
        self.groupBox.setTitle(_translate("Form", "测试设置"))
        self.groupBox_2.setTitle(_translate("Form", "用例选择"))
        self.checkBox_12.setText(_translate("Form", "WIR-未连接wifi-开关wifi"))
        self.checkBox_15.setText(_translate("Form", "WIR-已连接wifi-开关wifi"))
        self.checkBox_13.setText(_translate("Form", "WIR-未连接wifi-开关CCS"))
        self.checkBox_5.setText(_translate("Form", "WIR-已连接wifi-开关CCS"))
        self.checkBox_10.setText(_translate("Form", "WIR-wifi重连"))
        self.checkBox.setText(_translate("Form", "WIR-未连接wifi-重启TCU"))
        self.checkBox_4.setText(_translate("Form", "WIR-已连接wifi-重启TCU"))
        self.checkBox_6.setText(_translate("Form", "WIR-未连接wifi-重启ECG"))
        self.checkBox_9.setText(_translate("Form", "WIR-已连接wifi-重启ECG"))
        self.checkBox_3.setText(_translate("Form", "WIR-未连接wifi-断电重启"))
        self.checkBox_14.setText(_translate("Form", "WIR-已连接wifi-断电重启"))
        self.checkBox_16.setText(_translate("Form", "WIR-未连接wifi-重启IVI"))
        self.checkBox_17.setText(_translate("Form", "WIR-已连接wifi-重启IVI"))
        self.checkBox_7.setText(_translate("Form", "WIR-未连接wifi-恢复出厂"))
        self.checkBox_11.setText(_translate("Form", "WIR-已连接wifi-恢复出厂"))
        self.checkBox_2.setText(_translate("Form", "WIR-未连接wifi-Standby"))
        self.checkBox_8.setText(_translate("Form", "WIR-已连接wifi-Standby"))
        self.checkBox_18.setText(_translate("Form", "WIR-未连接wifi-STR"))
        self.checkBox_19.setText(_translate("Form", "WIR-已连接wifi-STR"))
        self.checkBox_20.setText(_translate("Form", "WIR-未连接wifi-深度休眠"))
        self.checkBox_21.setText(_translate("Form", "WIR-已连接wifi-深度休眠"))
        self.checkBox_22.setText(_translate("Form", "Ex-未连接wifi-开关CCS"))
        self.checkBox_23.setText(_translate("Form", "Ex-已连接wifi-开关CCS"))
        self.checkBox_24.setText(_translate("Form", "Ex-wifi重连"))
        self.checkBox_25.setText(_translate("Form", "Ex-未连接wifi-重启TCU"))
        self.checkBox_26.setText(_translate("Form", "Ex-已连接wifi-重启TCU"))
        self.checkBox_27.setText(_translate("Form", "Ex-未连接wifi-重启ECG"))
        self.checkBox_28.setText(_translate("Form", "Ex-已连接wifi-重启ECG"))
        self.checkBox_29.setText(_translate("Form", "Ex-未连接wifi-断电重启"))
        self.checkBox_30.setText(_translate("Form", "Ex-已连接wifi-断电重启"))
        self.checkBox_31.setText(_translate("Form", "Ex-未连接wifi-重启IVI"))
        self.checkBox_32.setText(_translate("Form", "Ex-已连接wifi-重启IVI"))
        self.checkBox_33.setText(_translate("Form", "Ex-未连接wifi-恢复出厂"))
        self.checkBox_34.setText(_translate("Form", "Ex-已连接wifi-恢复出厂"))
        self.checkBox_35.setText(_translate("Form", "Ex-未连接wifi-Standby"))
        self.checkBox_36.setText(_translate("Form", "Ex-已连接wifi-Standby"))
        self.checkBox_37.setText(_translate("Form", "Ex-未连接wifi-STR"))
        self.checkBox_38.setText(_translate("Form", "Ex-已连接wifi-STR"))
        self.checkBox_39.setText(_translate("Form", "Ex-未连接wifi-深度休眠"))
        self.checkBox_40.setText(_translate("Form", "Ex-已连接wifi-深度休眠"))
        self.pushButton_5.setText(_translate("Form", "开始测试"))
        self.pushButton_6.setText(_translate("Form", "结束测试"))
        self.pushButton_7.setText(_translate("Form", "连接ECG"))
        self.pushButton_16.setText(_translate("Form", "断开ECG"))
        self.pushButton_8.setText(_translate("Form", "连接TCU"))
        self.pushButton_17.setText(_translate("Form", "断开TCU"))
        self.pushButton_20.setText(_translate("Form", "连接串口"))
        self.pushButton_21.setText(_translate("Form", "断开串口"))
        self.label_56.setText(_translate("Form", "串口号"))
        self.label_57.setText(_translate("Form", "波特率"))
        self.radioButton.setText(_translate("Form", "时长设置（h）"))
        self.radioButton_2.setText(_translate("Form", "次数设置(次)"))
        self.pushButton_13.setText(_translate("Form", "连接CAN0"))
        self.pushButton_19.setText(_translate("Form", "连接CAN1"))
        self.pushButton_18.setText(_translate("Form", "断开CAN0"))
        self.pushButton_15.setText(_translate("Form", "断开CAN1"))
        self.label_2.setText(_translate("Form", "     CAN类型"))
        self.label_3.setText(_translate("Form", "     CAN类型"))
        self.comboBox.setItemText(0, _translate("Form", "CAN"))
        self.comboBox.setItemText(1, _translate("Form", "CANFD"))
        self.comboBox_2.setItemText(0, _translate("Form", "CAN"))
        self.comboBox_2.setItemText(1, _translate("Form", "CANFD"))
        self.label_53.setText(_translate("Form", "  仲裁波特率"))
        self.label_54.setText(_translate("Form", "  仲裁波特率"))
        self.comboBox_8.setItemText(0, _translate("Form", "500k"))
        self.comboBox_8.setItemText(1, _translate("Form", "250k"))
        self.comboBox_7.setItemText(0, _translate("Form", "500k"))
        self.comboBox_7.setItemText(1, _translate("Form", "250k"))
        self.label_52.setText(_translate("Form", " 数据波特率"))
        self.label_55.setText(_translate("Form", " 数据波特率"))
        self.comboBox_6.setItemText(0, _translate("Form", "2M"))
        self.comboBox_6.setItemText(1, _translate("Form", "1M"))
        self.comboBox_5.setItemText(0, _translate("Form", "2M"))
        self.comboBox_5.setItemText(1, _translate("Form", "1M"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "压力测试"))
        self.pushButton_9.setText(_translate("Form", "获取包名"))
        self.pushButton_10.setText(_translate("Form", "添加"))
        self.pushButton_11.setText(_translate("Form", "取消"))
        self.label_6.setText(_translate("Form", "包名列表"))
        self.label_7.setText(_translate("Form", "白名单"))
        self.label_8.setText(_translate("Form", "执行时长设置（h）"))
        self.label_10.setText(_translate("Form", "事件类型百分比"))
        self.radioButton_3.setText(_translate("Form", "执行白名单"))
        self.radioButton_4.setText(_translate("Form", "执行白名单以外的包"))
        self.radioButton_5.setText(_translate("Form", "全部执行"))
        self.radioButton_6.setText(_translate("Form", "执行单包"))
        self.label_11.setText(_translate("Form", "调试类参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "monkey测试"))
        self.pushButton_12.setText(_translate("Form", "获取性能数据"))
        self.groupBox_3.setTitle(_translate("Form", "设备内存"))
        self.groupBox_4.setTitle(_translate("Form", "设备CPU"))
        self.groupBox_5.setTitle(_translate("Form", "网络信息"))
        self.groupBox_6.setTitle(_translate("Form", "显示器内存信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "性能测试"))
        self.groupBox_7.setTitle(_translate("Form", "设备信息:"))
        self.label.setText(_translate("Form", "品牌车型:"))
        self.label_36.setText(_translate("Form", "设备型号:"))
        self.label_37.setText(_translate("Form", "sdk版本:"))
        self.label_42.setText(_translate("Form", self.get_device_info()["serial"]))
        self.label_46.setText(_translate("Form", self.get_device_info()["arch"]))
        self.label_48.setText(_translate("Form", str(self.get_device_info()["sdk"])))
        self.label_9.setText(_translate("Form", "设备品牌:"))
        self.label_45.setText(_translate("Form", self.get_device_info()["brand"]))
        self.label_40.setText(_translate("Form", "SOC版本:"))
        self.label_49.setText(_translate("Form", "GACXXXX_A8E_AVNT_SH_240206.SOP2.01_D_97"))
        self.label_50.setText(_translate("Form", "A8E_IC2014_01_21.100_231023_R"))
        self.label_41.setText(_translate("Form", "MCU版本:"))
        self.label_47.setText(_translate("Form", "28:0f:eb:50:06:49"))
        self.label_39.setText(_translate("Form", "硬件地址:"))
        self.label_4.setText(_translate("Form", "安卓版本:"))
        self.label_43.setText(_translate("Form", str(self.get_device_info()["version"])))
        self.label_38.setText(_translate("Form", "IP地址:"))
        self.label_51.setText(_translate("Form", "192.168.7.16"))
        self.label_5.setText(_translate("Form", "设备序列号:"))
        self.label_44.setText(_translate("Form", self.get_device_info()["serial"]))
        self.groupBox_8.setTitle(_translate("Form", "电池信息"))
        self.label_20.setText(_translate("Form", "是否为直流电:"))
        self.label_21.setText(_translate("Form", "充电状态:"))
        self.label_22.setText(_translate("Form", "健康状态:"))
        self.label_23.setText(_translate("Form", "电池是否存在:"))
        self.label_24.setText(_translate("Form", "电池电量："))
        self.label_25.setText(_translate("Form", "电池电压："))
        self.label_26.setText(_translate("Form", "电池温度："))
        self.label_27.setText(_translate("Form", "电池容量："))
        self.label_28.setText(_translate("Form", "正在充电"))
        self.label_31.setText(_translate("Form", "良好"))
        self.label_29.setText(_translate("Form", "存在"))
        self.label_30.setText(_translate("Form", "直流"))
        self.label_32.setText(_translate("Form", "100"))
        self.label_33.setText(_translate("Form", "80%"))
        self.label_34.setText(_translate("Form", "292开尔文"))
        self.label_35.setText(_translate("Form", "1400mV"))
        self.groupBox_9.setTitle(_translate("Form", "显示屏信息"))
        self.label_12.setText(_translate("Form", "分辨率："))
        self.label_13.setText(_translate("Form", "1920x1080"))
        self.groupBox_10.setTitle(_translate("Form", "内存"))
        self.label_14.setText(_translate("Form", "9815556"))
        self.label_15.setText(_translate("Form", "总内存："))
        self.groupBox_11.setTitle(_translate("Form", "CPU"))
        self.label_16.setText(_translate("Form", "核数："))
        self.label_17.setText(_translate("Form", "7"))
        self.label_18.setText(_translate("Form", "型号："))
        self.label_19.setText(_translate("Form", "Qualcomm Technologies, Inc SA8155"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "设备详情"))

    def _on_test_finished(self, error_msg):
        """测试完成回调（在主线程中执行）"""
        self.pushButton_5.setEnabled(True)
        if error_msg:
            QtWidgets.QMessageBox.critical(self.listWidget.window(), "安卓连接", error_msg)
        else:
            Logger.info("测试已完成")

    def _ui_log_sink(self, log_text: str):
        self.new_log_signal.emit(log_text)

    def append_log_to_list(self, log_str):
        if self.listWidget is None:
            return
        item = QtWidgets.QListWidgetItem(log_str)
        # ERROR红色，INFO默认黑色
        if "ERROR" in log_str:
            item.setForeground(QtCore.Qt.red)
        # 固定行高
        item.setSizeHint(QtCore.QSize(item.sizeHint().width(), 20))
        self.listWidget.addItem(item)
        # 自动滚动到底部
        self.listWidget.scrollToBottom()

    def get_checkBox_12(self):
        return self.checkBox_12.isChecked()

    def get_checkBox_15(self):
        return self.checkBox_15.isChecked()

    def get_checkBox_13(self):
        return self.checkBox_13.isChecked()
        
    def get_checkBox_5(self):
        return self.checkBox_5.isChecked()
        
    def get_checkBox_10(self):
        return self.checkBox_10.isChecked()

    def get_checkBox(self):
        return self.checkBox.isChecked()
        
    def get_checkBox_4(self):
        return self.checkBox_4.isChecked()
        
    def get_checkBox_6(self):
        return self.checkBox_6.isChecked()
        
    def get_checkBox_9(self):
        return self.checkBox_9.isChecked()

    def get_checkBox_3(self):
        return self.checkBox_3.isChecked()
        
    def get_checkBox_14(self):
        return self.checkBox_14.isChecked()

    def get_checkBox_16(self):
        return self.checkBox_16.isChecked()
        
    def get_checkBox_17(self):
        return self.checkBox_17.isChecked()

    def get_checkBox_7(self):
        return self.checkBox_7.isChecked()

    def get_checkBox_11(self):
        return self.checkBox_11.isChecked()

    def get_checkBox_2(self):
        return self.checkBox_2.isChecked()

    def get_checkBox_8(self):
        return self.checkBox_8.isChecked()

    def get_checkBox_18(self):
        return self.checkBox_18.isChecked()

    def get_checkBox_19(self):
        return self.checkBox_19.isChecked()
        
    def get_checkBox_20(self):
        return self.checkBox_20.isChecked()

    def get_checkBox_21(self):
        return self.checkBox_21.isChecked()

    def get_checkBox_22(self):
        return self.checkBox_22.isChecked()
           
    def get_checkBox_23(self):
        return self.checkBox_23.isChecked()
        
    def get_checkBox_24(self):
        return self.checkBox_24.isChecked()
        
    def get_checkBox_25(self):
        return self.checkBox_25.isChecked()
        
    def get_checkBox_26(self):
        return self.checkBox_26.isChecked()
        
    def get_checkBox_27(self):
        return self.checkBox_27.isChecked()
        
    def get_checkBox_28(self):
        return self.checkBox_28.isChecked()
        
    def get_checkBox_29(self):
        return self.checkBox_29.isChecked()
        
    def get_checkBox_30(self):
        return self.checkBox_30.isChecked()
        
    def get_checkBox_31(self):
        return self.checkBox_31.isChecked()
        
    def get_checkBox_32(self):
        return self.checkBox_32.isChecked()
        
    def get_checkBox_33(self):
        return self.checkBox_33.isChecked()
        
    def get_checkBox_34(self):
        return self.checkBox_34.isChecked()
  
    def get_checkBox_35(self):
        return self.checkBox_35.isChecked()
    
    def get_checkBox_36(self):
        return self.checkBox_36.isChecked()
        
    def get_checkBox_37(self):
        return self.checkBox_37.isChecked()
        
    def get_checkBox_38(self):
        return self.checkBox_38.isChecked()
        
    def get_checkBox_39(self):
        return self.checkBox_39.isChecked()
        
    def get_checkBox_40(self):
        return self.checkBox_40.isChecked()

    def get_pushButton_5(self):
        # 防止重复点击
        if adb.device_list() == []:
            QtWidgets.QMessageBox.critical(self.listWidget.window(), "adb连接", "请检查adb连接！")
        if self._test_thread is not None and self._test_thread.is_alive():
            QtWidgets.QMessageBox.warning(self.listWidget.window(), "提示", "测试正在进行中，请先停止当前测试！")
            return
        # 在主线程中读取所有checkbox状态（避免跨线程访问Qt控件）
        test_plan = []
        if self.checkBox_12.isChecked():
            test_plan.append(("WIR-未连接wifi-开关wifi", self.reopen_wifi_no_wifi_test))
        if self.checkBox_15.isChecked():
            test_plan.append(("WIR-已连接wifi-开关wifi", self.reopen_wifi_wifi_test))
        if self.checkBox_13.isChecked():
            test_plan.append(("WIR-未连接wifi-开关CCS", self.reopen_ccs_no_wifi_test))
        if self.checkBox_5.isChecked():
            test_plan.append(("WIR-已连接wifi-开关CCS", self.reopen_ccs_wifi_test))
        if self.checkBox_10.isChecked():
            test_plan.append(("WIR-wifi重连", self.reconnect_wifi_test))
        if self.checkBox.isChecked():
            test_plan.append(("WIR-未连接wifi-重启TCU", self.tcu_reset_no_wifi_test))
        if self.checkBox_4.isChecked():
            test_plan.append(("WIR-已连接wifi-重启TCU", self.tcu_reset_wifi_test))
        if self.checkBox_6.isChecked():
            test_plan.append(("WIR-未连接wifi-重启ECG", self.ecg_reset_no_wifi_test))
        if self.checkBox_9.isChecked():
            test_plan.append(("WIR-已连接wifi-重启ECG", self.ecg_reset_wifi_test))
        if self.checkBox_3.isChecked():
            test_plan.append(("WIR-未连接wifi-断电重启", self.power_reset_no_wifi_test))
        if self.checkBox_14.isChecked():
            test_plan.append(("WIR-已连接wifi-断电重启", self.power_reset_wifi_test))
        if self.checkBox_16.isChecked():
            test_plan.append(("WIR-未连接wifi-重启IVI", self.ivi_reset_no_wifi_test))
        if self.checkBox_17.isChecked():
            test_plan.append(("WIR-已连接wifi-重启IVI", self.ivi_reset_wifi_test))
        if self.checkBox_7.isChecked():
            test_plan.append(("WIR-未连接wifi-恢复出厂", self.system_reset_no_wifi_test))
        if self.checkBox_11.isChecked():
            test_plan.append(("WIR-已连接wifi-恢复出厂", self.system_reset_wifi_test))
        if self.checkBox_2.isChecked():
            test_plan.append(("WIR-未连接wifi-Standby", self.standby_no_wifi_test))
        if self.checkBox_8.isChecked():
            test_plan.append(("WIR-已连接wifi-Standby", self.standby_wifi_test))
        if self.checkBox_18.isChecked():
            test_plan.append(("WIR-未连接wifi-STR", self.str_no_wifi_test))
        if self.checkBox_19.isChecked():
            test_plan.append(("WIR-已连接wifi-STR", self.str_wifi_test))
        if self.checkBox_20.isChecked():
            test_plan.append(("WIR-未连接wifi-深度休眠", self.sleep_no_wifi_test))
        if self.checkBox_21.isChecked():
            test_plan.append(("WIR-已连接wifi-深度休眠", self.sleep_wifi_test))
        if self.checkBox_22.isChecked():
            test_plan.append(("Ex-未连接wifi-开关CCS", self.reopen_ccs_no_wifi_test_ex))
        if self.checkBox_23.isChecked():
            test_plan.append(("Ex-已连接wifi-开关CCS", self.reopen_ccs_wifi_test_ex))
        if self.checkBox_24.isChecked():
            test_plan.append(("Ex-wifi重连", self.reconnect_wifi_test_ex))
        if self.checkBox_25.isChecked():
            test_plan.append(("Ex-未连接wifi-重启TCU", self.tcu_reset_no_wifi_test_ex))
        if self.checkBox_26.isChecked():
            test_plan.append(("Ex-已连接wifi-重启TCU", self.tcu_reset_wifi_test_ex))
        if self.checkBox_27.isChecked():
            test_plan.append(("Ex-未连接wifi-重启ECG", self.ecg_reset_no_wifi_test_ex))
        if self.checkBox_28.isChecked():
            test_plan.append(("Ex-已连接wifi-重启ECG", self.ecg_reset_wifi_test_ex))
        if self.checkBox_29.isChecked():
            test_plan.append(("Ex-未连接wifi-断电重启", self.power_reset_no_wifi_test_ex))
        if self.checkBox_30.isChecked():
            test_plan.append(("Ex-已连接wifi-断电重启", self.power_reset_wifi_test_ex))
        if self.checkBox_31.isChecked():
            test_plan.append(("Ex-未连接wifi-重启IVI", self.ivi_reset_no_wifi_test_ex))
        if self.checkBox_32.isChecked():
            test_plan.append(("Ex-已连接wifi-重启IVI", self.ivi_reset_wifi_test_ex))
        if self.checkBox_33.isChecked():
            test_plan.append(("Ex-未连接wifi-恢复出厂", self.system_reset_no_wifi_test_ex))
        if self.checkBox_34.isChecked():
            test_plan.append(("Ex-已连接wifi-恢复出厂", self.system_reset_wifi_test_ex))
        if self.checkBox_35.isChecked():
            test_plan.append(("Ex-未连接wifi-Standby", self.standby_no_wifi_test_ex))
        if self.checkBox_36.isChecked():
            test_plan.append(("Ex-已连接wifi-Standby", self.standby_wifi_test_ex))
        if self.checkBox_37.isChecked():
            test_plan.append(("Ex-未连接wifi-STR", self.str_no_wifi_test_ex))
        if self.checkBox_38.isChecked():
            test_plan.append(("Ex-已连接wifi-STR", self.str_wifi_test_ex))
        if self.checkBox_39.isChecked():
            test_plan.append(("Ex-未连接wifi-深度休眠", self.sleep_no_wifi_test_ex))
        if self.checkBox_40.isChecked():
            test_plan.append(("Ex-已连接wifi-深度休眠", self.sleep_wifi_test_ex))
        if not test_plan:
            QtWidgets.QMessageBox.warning(self.listWidget.window(), "提示", "请至少勾选一个测试项！")
            return
        self._test_stop_flag = False
        self.pushButton_5.setEnabled(False)
        self._test_thread = threading.Thread(target=self._run_tests_worker, args=(test_plan,), daemon=True)
        self._test_thread.start()

    def _run_tests_worker(self, test_plan):
        """测试执行工作线程"""
        try:
            Logger.info("开始测试")
            self.devices_init()
            for name, test_fn in test_plan:
                if self._test_stop_flag:
                    Logger.info("用户已请求停止测试，剩余测试项未执行")
                    break
                Logger.info(f"========== 开始执行: {name} ==========")
                test_fn(count=600)
                Logger.info(f"========== 完成: {name} ==========")
        except Exception as e:
            Logger.error(f"测试执行异常: {e}")
            self.test_finished_signal.emit("请检查adb连接是否成功！")
            return
        self.test_finished_signal.emit("")

    def get_pushButton_6(self):
        self._test_stop_flag = True
        Logger.info("已请求停止测试，等待当前测试项完成后停止")
    def get_pushButton_7(self):
        return self.pushButton_7.isChecked()
    def get_pushButton_16(self):
        return self.pushButton_16.isChecked()
    def get_pushButton_8(self):
        return self.pushButton_8.isChecked()
    def get_pushButton_17(self):
        return self.pushButton_17.isChecked()
    def get_pushButton_20(self):
        try:
            port = self.lineEdit_4.text()
            if self.lineEdit_5.text() == "":
                baudrate = 9600
            else:
                baudrate = int(self.lineEdit_5.text())
            self.com_start(port, baudrate)
        except Exception as e:
            QtWidgets.QMessageBox.critical(self.listWidget.window(), "串口错误", "请检查串口连接！")

    def get_pushButton_21(self):
        self.com_stop()

    def get_pushButton_13(self):
        try:
            if self.comboBox.currentText() == "CAN":
                can_type = CanMessageType.CAN
            elif self.comboBox.currentText() == "CANFD":
                can_type = CanMessageType.CANFD
            if self.comboBox_8.currentText() == "500k":
                can_bitrate = CanBitRate.CAN_500K
            elif self.comboBox_8.currentText() == "250k":
                can_bitrate = CanBitRate.CAN_250K
            if self.comboBox_6.currentText() == "2M":
                can_fd_bitrate = CanFDDataBitRate.CANFD_2M
            elif self.comboBox_6.currentText() == "1M":
                can_fd_bitrate = CanFDDataBitRate.CANFD_1M
            t = threading.Thread(target=send_can_start_device, args=(ZCAN_USBCANFD_200U, CanChannelNum.CAN1, can_bitrate, can_fd_bitrate, can_type,))
            t.start()

        except Exception as e:
            QtWidgets.QMessageBox.critical(self.listWidget.window(), "CAN设备错误", "请检查CAN连接！是否被其他软件占用！")

    def get_pushButton_19(self):
        if self.pushButton_15.isChecked():
            set_power_status(3)
    def get_pushButton_18(self):
        if self.comboBox_2.currentText() == "CAN":
            can_type = CanMessageType.CAN
        elif self.comboBox_2.currentText() == "CANFD":
            can_type = CanMessageType.CANFD
        if self.comboBox_7.currentText() == "500k":
            can_bitrate = CanBitRate.CAN_500K
        elif self.comboBox_7.currentText() == "250k":
            can_bitrate = CanBitRate.CAN_250K
        if self.comboBox_5.currentText() == "2M":
            can_fd_bitrate = CanFDDataBitRate.CANFD_2M
        elif self.comboBox_5.currentText() == "1M":
            can_fd_bitrate = CanFDDataBitRate.CANFD_1M
        t = threading.Thread(target=send_can_start_device, args=(ZCAN_USBCANFD_200U, CanChannelNum.CAN2, can_bitrate, can_fd_bitrate, can_type,))
        t.start()

    def get_pushButton_15(self):
        if self.pushButton_15.isChecked():
            powerStatus = 3

    def get_comboBox(self):
        return self.comboBox.currentText()

    def get_comboBox_2(self):
        return self.comboBox_2.currentText()

    def get_comboBox_8(self):
        return self.comboBox_8.currentText()

    def get_comboBox_7(self):
        return self.comboBox_7.currentText()

    def get_comboBox_6(self):
            return self.comboBox_6.currentText()
    
    def get_comboBox_5(self):
        return self.comboBox_5.currentText()

class MainWindow(QtWidgets.QMainWindow):
    """主窗口：使用 QMainWindow，自带最小化 / 最大化 / 关闭按钮，可拖拽边缘自由缩放。"""

    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.setWindowTitle("压力测试工具")
        # 显式开启最小化 / 最大化 / 关闭按钮
        self.setWindowFlags(
            self.windowFlags()
            | QtCore.Qt.WindowMinimizeButtonHint
            | QtCore.Qt.WindowMaximizeButtonHint
            | QtCore.Qt.WindowCloseButtonHint
        )
        # 中央部件：界面全部放在它上面，窗口缩放时自动铺满
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget(self.centralwidget)
        self.ui = Ui_Form()
        self.ui.setupUi(self.centralwidget)
        self.resize(1176, 685)
        # 可选：底部状态栏
        self.statusBar().showMessage("就绪")

    def closeEvent(self, event):
        """关闭窗口时尝试停止正在进行的测试线程"""
        try:
            self.ui._test_stop_flag = True
        except Exception:
            pass
        super().closeEvent(event)


if __name__ == "__main__":
    # ========== 严格顺序：1.初始化日志实例 ==========
    log = Logger()

    # ========== 2.启动QT ==========
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())